background            #161412
background_opacity    0.97

selection_background  #3c3836

# Font configuration
font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

modify_font line_height 115%

window_padding_width 8

repaint_delay 10
input_delay 3
sync_to_monitor yes
