background            #0f0f0f
foreground            #e0e0e0
background_opacity    0.95
selection_background  #333333
selection_foreground  #ffffff

font_family      JetBrains Mono Nerd Font
font_size        13.0
modify_font      line_height 115%
disable_ligatures never

repaint_delay    8
input_delay      1
sync_to_monitor  yes

cursor_shape          block
cursor_blink_interval 0
enable_audio_bell     no
window_padding_width  12
confirm_os_window_close 0

tab_bar_style        powerline
active_tab_foreground   #000
active_tab_background   #eee
inactive_tab_foreground #444
inactive_tab_background #0f0f0f

