set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g history-limit 1000000

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

set -g status-style "bg=#181820,fg=#c5c9c5"
set -g status-left "#[fg=#8a9a7b,bold] #S "
set -g status-right "#[fg=#a292a3] %H:%M #[fg=#8ba4b1,bold] #H "
setw -g window-status-current-style "fg=#e6c384,bold,bg=#2d4f67"
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
set -g pane-border-style "fg=#1f1f28"
set -g pane-active-border-style "fg=#2d4f67"
